// <auto-generated />
using System;
using Lex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lex.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715171413_TrabajoTpt")]
    partial class TrabajoTpt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lex.Api.Domain.Entities.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarreraId"));

                    b.Property<string>("AreaConocimiento")
                        .HasColumnType("text")
                        .HasColumnName("area_conocimiento");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("integer")
                        .HasColumnName("institucion_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("CarreraId");

                    b.HasIndex("InstitucionId");

                    b.ToTable("carrera");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.CatalogoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<bool>("RequiereSupervisor")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_supervisor");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_servicio");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("catalogo_servicio");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.CatalogoServicioCarrera", b =>
                {
                    b.Property<int>("CatalogoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("catalogo_servicio_id");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<int>("AnioMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("anio_minimo");

                    b.HasKey("CatalogoServicioId", "CarreraId");

                    b.HasIndex("CarreraId");

                    b.ToTable("catalogo_servicio_carrera");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Consentimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AceptadoPorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("aceptado_por_usuario_id");

                    b.Property<DateTime>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aceptacion");

                    b.Property<string>("IpAceptacion")
                        .HasColumnType("text")
                        .HasColumnName("ip_aceptacion");

                    b.Property<string>("TextoCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_completo");

                    b.Property<int>("TrabajoSaludId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_salud_id");

                    b.HasKey("Id");

                    b.HasIndex("AceptadoPorUsuarioId");

                    b.HasIndex("TrabajoSaludId")
                        .IsUnique();

                    b.ToTable("consentimiento");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.DatosEmpresa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Cuit")
                        .HasColumnType("text")
                        .HasColumnName("cuit");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rubro")
                        .HasColumnType("text")
                        .HasColumnName("rubro");

                    b.HasKey("UsuarioId");

                    b.ToTable("datos_empresa");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.DatosParticular", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Dni")
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.HasKey("UsuarioId");

                    b.ToTable("datos_particular");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.EstudianteCarrera", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<string>("DocumentoComprobante")
                        .HasColumnType("text")
                        .HasColumnName("documento_comprobante");

                    b.Property<int>("EstadoVerificacion")
                        .HasColumnType("integer")
                        .HasColumnName("estado_verificacion");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_verificacion");

                    b.HasKey("EstudianteId", "CarreraId");

                    b.HasIndex("CarreraId");

                    b.ToTable("estudiante_carrera");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Institucion", b =>
                {
                    b.Property<int>("InstitucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("institucion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstitucionId"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.Property<int>("TipoInstitucionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_institucion_id");

                    b.HasKey("InstitucionId");

                    b.HasIndex("TipoInstitucionId");

                    b.ToTable("institucion");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_responsable_id");

                    b.Property<string>("ContactoEmergenciaNombre")
                        .HasColumnType("text")
                        .HasColumnName("contacto_emergencia_nombre");

                    b.Property<string>("ContactoEmergenciaTelefono")
                        .HasColumnType("text")
                        .HasColumnName("contacto_emergencia_telefono");

                    b.Property<string>("Dni")
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<bool>("EsTitular")
                        .HasColumnType("boolean")
                        .HasColumnName("es_titular");

                    b.Property<string>("Especie")
                        .HasColumnType("text")
                        .HasColumnName("especie");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NotasRelevantes")
                        .HasColumnType("text")
                        .HasColumnName("notas_relevantes");

                    b.Property<string>("Raza")
                        .HasColumnType("text")
                        .HasColumnName("raza");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteResponsableId");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComisionLex")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("comision_lex");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaLiberacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_liberacion");

                    b.Property<DateTime?>("FechaRetencion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_retencion");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoEstudiante")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_estudiante");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_total");

                    b.Property<decimal>("PorcentajeComision")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_comision");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId")
                        .IsUnique();

                    b.ToTable("pago");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilAgencia", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("NombreAgencia")
                        .HasColumnType("text")
                        .HasColumnName("nombre_agencia");

                    b.Property<string>("Rubro")
                        .HasColumnType("text")
                        .HasColumnName("rubro");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("text")
                        .HasColumnName("sitio_web");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_agencia");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilCliente", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_cliente");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilEstudiante", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("AnioCursado")
                        .HasColumnType("integer")
                        .HasColumnName("anio_cursado");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("calificacion_promedio");

                    b.Property<int>("CantidadTrabajos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_trabajos");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_estudiante");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Postulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_postulacion");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<decimal?>("MontoPropuesto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_propuesto");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("postulacion");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ProfesionalSupervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("especialidad");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<int?>("InstitucionId")
                        .HasColumnType("integer")
                        .HasColumnName("institucion_id");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matricula");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.ToTable("profesional_supervisor");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("autor_usuario_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<int>("ReceptorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("receptor_usuario_id");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.HasKey("Id");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("ReceptorUsuarioId");

                    b.HasIndex("TrabajoId", "AutorUsuarioId")
                        .IsUnique();

                    b.ToTable("resena");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("rol");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("servicio", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<decimal?>("PresupuestoEstimado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("presupuesto_estimado");

                    b.Property<string>("TipoServicio")
                        .HasColumnType("text")
                        .HasColumnName("tipo_servicio");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("solicitud");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TipoInstitucion", b =>
                {
                    b.Property<int>("TipoInstitucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_institucion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoInstitucionId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("TipoInstitucionId");

                    b.ToTable("tipo_institucion");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("DescripcionSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion_snapshot");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal>("PrecioAcordado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_acordado");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("servicio_id");

                    b.Property<string>("TituloSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("trabajo", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("estado_anterior");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer")
                        .HasColumnName("trabajo_id");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("trabajo_historial");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("RolId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_rol");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ServicioClase", b =>
                {
                    b.HasBaseType("Lex.Api.Domain.Entities.Servicio");

                    b.Property<int?>("CantidadSesionesPaquete")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_sesiones_paquete");

                    b.Property<int>("DuracionMinutosSesion")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos_sesion");

                    b.Property<bool>("EsPaquete")
                        .HasColumnType("boolean")
                        .HasColumnName("es_paquete");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("materia");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.ToTable("servicio_clase", (string)null);
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ServicioProyectoCerrado", b =>
                {
                    b.HasBaseType("Lex.Api.Domain.Entities.Servicio");

                    b.Property<int>("CatalogoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("catalogo_servicio_id");

                    b.Property<string>("FormatoEntrega")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato_entrega");

                    b.Property<int>("PlazoEntregaDias")
                        .HasColumnType("integer")
                        .HasColumnName("plazo_entrega_dias");

                    b.Property<int>("RevisionesIncluidas")
                        .HasColumnType("integer")
                        .HasColumnName("revisiones_incluidas");

                    b.HasIndex("CatalogoServicioId");

                    b.ToTable("servicio_proyecto_cerrado", (string)null);
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ServicioSalud", b =>
                {
                    b.HasBaseType("Lex.Api.Domain.Entities.Servicio");

                    b.Property<int>("CatalogoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("catalogo_servicio_id");

                    b.Property<int>("DuracionMinutosSesion")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos_sesion");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id");

                    b.HasIndex("CatalogoServicioId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("servicio_salud", (string)null);
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoClase", b =>
                {
                    b.HasBaseType("Lex.Api.Domain.Entities.Trabajo");

                    b.Property<int>("CantidadSesionesTotales")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_sesiones_totales");

                    b.Property<int>("DuracionMinutosSesionSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos_sesion_snapshot");

                    b.Property<bool>("EsPaqueteSnapshot")
                        .HasColumnType("boolean")
                        .HasColumnName("es_paquete_snapshot");

                    b.Property<string>("MateriaSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("materia_snapshot");

                    b.Property<string>("ModalidadSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad_snapshot");

                    b.Property<string>("NivelSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel_snapshot");

                    b.Property<int>("SesionesCompletadas")
                        .HasColumnType("integer")
                        .HasColumnName("sesiones_completadas");

                    b.ToTable("trabajo_clase", (string)null);
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoProyectoCerrado", b =>
                {
                    b.HasBaseType("Lex.Api.Domain.Entities.Trabajo");

                    b.Property<string>("FormatoEntregaSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato_entrega_snapshot");

                    b.Property<DateTime>("PlazoEntregaFecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plazo_entrega_fecha");

                    b.Property<int>("RevisionesMaximas")
                        .HasColumnType("integer")
                        .HasColumnName("revisiones_maximas");

                    b.Property<int>("RevisionesUsadas")
                        .HasColumnType("integer")
                        .HasColumnName("revisiones_usadas");

                    b.ToTable("trabajo_proyecto_cerrado", (string)null);
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoSalud", b =>
                {
                    b.HasBaseType("Lex.Api.Domain.Entities.Trabajo");

                    b.Property<int>("CatalogoServicioAnioMinimoSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("catalogo_servicio_anio_minimo_snapshot");

                    b.Property<int>("CatalogoServicioIdSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("catalogo_servicio_id_snapshot");

                    b.Property<string>("CatalogoServicioNombreSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("catalogo_servicio_nombre_snapshot");

                    b.Property<int?>("ConsentimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("consentimiento_id");

                    b.Property<int>("DuracionMinutosSesionSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos_sesion_snapshot");

                    b.Property<string>("ModalidadSaludSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modalidad_salud_snapshot");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int>("SupervisorIdSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("supervisor_id_snapshot");

                    b.Property<string>("SupervisorMatriculaSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supervisor_matricula_snapshot");

                    b.Property<string>("SupervisorNombreSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supervisor_nombre_snapshot");

                    b.HasIndex("ConsentimientoId")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.ToTable("trabajo_salud", (string)null);
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Carrera", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Institucion", "Institucion")
                        .WithMany("Carreras")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.CatalogoServicioCarrera", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.CatalogoServicio", "CatalogoServicio")
                        .WithMany("Carreras")
                        .HasForeignKey("CatalogoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("CatalogoServicio");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Consentimiento", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "AceptadoPor")
                        .WithMany()
                        .HasForeignKey("AceptadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AceptadoPor");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.DatosEmpresa", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilCliente", "PerfilCliente")
                        .WithOne("DatosEmpresa")
                        .HasForeignKey("Lex.Api.Domain.Entities.DatosEmpresa", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilCliente");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.DatosParticular", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilCliente", "PerfilCliente")
                        .WithOne("DatosParticular")
                        .HasForeignKey("Lex.Api.Domain.Entities.DatosParticular", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilCliente");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.EstudianteCarrera", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Carrera", "Carrera")
                        .WithMany("EstudianteCarreras")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("EstudianteCarreras")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Institucion", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.TipoInstitucion", "TipoInstitucion")
                        .WithMany("Instituciones")
                        .HasForeignKey("TipoInstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoInstitucion");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilCliente", "ClienteResponsable")
                        .WithMany("Pacientes")
                        .HasForeignKey("ClienteResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteResponsable");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Trabajo", "Trabajo")
                        .WithOne("Pago")
                        .HasForeignKey("Lex.Api.Domain.Entities.Pago", "TrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilAgencia", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilAgencia")
                        .HasForeignKey("Lex.Api.Domain.Entities.PerfilAgencia", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilCliente", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilCliente")
                        .HasForeignKey("Lex.Api.Domain.Entities.PerfilCliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilEstudiante", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilEstudiante")
                        .HasForeignKey("Lex.Api.Domain.Entities.PerfilEstudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Postulacion", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Postulaciones")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ProfesionalSupervisor", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Institucion", "Institucion")
                        .WithMany()
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Resena", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Autor")
                        .WithMany("ResenasComoAutor")
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Receptor")
                        .WithMany("ResenasComoReceptor")
                        .HasForeignKey("ReceptorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Trabajo", "Trabajo")
                        .WithMany("Resenas")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Receptor");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("Servicios")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilCliente", "Cliente")
                        .WithMany("Solicitudes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Trabajo", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.PerfilCliente", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("Trabajos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Servicio", "Servicio")
                        .WithMany("Trabajos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estudiante");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoHistorial", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Trabajo", "Trabajo")
                        .WithMany("Historiales")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TrabajoHistoriales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Trabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ServicioClase", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Servicio", null)
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.ServicioClase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ServicioProyectoCerrado", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.CatalogoServicio", "CatalogoServicio")
                        .WithMany()
                        .HasForeignKey("CatalogoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Servicio", null)
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.ServicioProyectoCerrado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatalogoServicio");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ServicioSalud", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.CatalogoServicio", "CatalogoServicio")
                        .WithMany()
                        .HasForeignKey("CatalogoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Servicio", null)
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.ServicioSalud", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.ProfesionalSupervisor", "Supervisor")
                        .WithMany("ServiciosSalud")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogoServicio");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoClase", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Trabajo", null)
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.TrabajoClase", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoProyectoCerrado", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Trabajo", null)
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.TrabajoProyectoCerrado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TrabajoSalud", b =>
                {
                    b.HasOne("Lex.Api.Domain.Entities.Consentimiento", "Consentimiento")
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.TrabajoSalud", "ConsentimientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lex.Api.Domain.Entities.Trabajo", null)
                        .WithOne()
                        .HasForeignKey("Lex.Api.Domain.Entities.TrabajoSalud", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lex.Api.Domain.Entities.Paciente", "Paciente")
                        .WithMany("TrabajosSalud")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consentimiento");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Carrera", b =>
                {
                    b.Navigation("EstudianteCarreras");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.CatalogoServicio", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Institucion", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("TrabajosSalud");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilCliente", b =>
                {
                    b.Navigation("DatosEmpresa");

                    b.Navigation("DatosParticular");

                    b.Navigation("Pacientes");

                    b.Navigation("Solicitudes");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.PerfilEstudiante", b =>
                {
                    b.Navigation("EstudianteCarreras");

                    b.Navigation("Postulaciones");

                    b.Navigation("Servicios");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.ProfesionalSupervisor", b =>
                {
                    b.Navigation("ServiciosSalud");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.TipoInstitucion", b =>
                {
                    b.Navigation("Instituciones");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Trabajo", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Pago");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Lex.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PerfilAgencia");

                    b.Navigation("PerfilCliente");

                    b.Navigation("PerfilEstudiante");

                    b.Navigation("ResenasComoAutor");

                    b.Navigation("ResenasComoReceptor");

                    b.Navigation("TrabajoHistoriales");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
