// <auto-generated />
using System;
using Lex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lex.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713000640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lex.Api.Entities.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarreraId"));

                    b.Property<string>("AreaConocimiento")
                        .HasColumnType("text")
                        .HasColumnName("area_conocimiento");

                    b.Property<int>("InstitucionId")
                        .HasColumnType("integer")
                        .HasColumnName("institucion_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("CarreraId");

                    b.HasIndex("InstitucionId");

                    b.ToTable("carrera");
                });

            modelBuilder.Entity("Lex.Api.Entities.Consentimiento", b =>
                {
                    b.Property<int>("IdConsentimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consentimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsentimiento"));

                    b.Property<bool>("Aceptado")
                        .HasColumnType("boolean")
                        .HasColumnName("aceptado");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aceptacion");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("integer")
                        .HasColumnName("id_trabajo");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<string>("SupervisorResponsable")
                        .HasColumnType("text")
                        .HasColumnName("supervisor_responsable");

                    b.Property<string>("TextoConsentimiento")
                        .HasColumnType("text")
                        .HasColumnName("texto_consentimiento");

                    b.HasKey("IdConsentimiento");

                    b.HasIndex("IdTrabajo")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.ToTable("consentimiento");
                });

            modelBuilder.Entity("Lex.Api.Entities.DatosEmpresa", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Cuit")
                        .HasColumnType("text")
                        .HasColumnName("cuit");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rubro")
                        .HasColumnType("text")
                        .HasColumnName("rubro");

                    b.HasKey("UsuarioId");

                    b.ToTable("datos_empresa");
                });

            modelBuilder.Entity("Lex.Api.Entities.DatosParticular", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Dni")
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.HasKey("UsuarioId");

                    b.ToTable("datos_particular");
                });

            modelBuilder.Entity("Lex.Api.Entities.EstudianteCarrera", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer")
                        .HasColumnName("carrera_id");

                    b.Property<string>("DocumentoComprobante")
                        .HasColumnType("text")
                        .HasColumnName("documento_comprobante");

                    b.Property<int>("EstadoVerificacion")
                        .HasColumnType("integer")
                        .HasColumnName("estado_verificacion");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_verificacion");

                    b.HasKey("EstudianteId", "CarreraId");

                    b.HasIndex("CarreraId");

                    b.ToTable("estudiante_carrera");
                });

            modelBuilder.Entity("Lex.Api.Entities.Institucion", b =>
                {
                    b.Property<int>("InstitucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("institucion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InstitucionId"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.Property<int>("TipoInstitucionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_institucion_id");

                    b.HasKey("InstitucionId");

                    b.HasIndex("TipoInstitucionId");

                    b.ToTable("institucion");
                });

            modelBuilder.Entity("Lex.Api.Entities.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PacienteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.HasKey("PacienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("Lex.Api.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<decimal>("ComisionLex")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("comision_lex");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaLiberacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_liberacion");

                    b.Property<DateTime?>("FechaRetencion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_retencion");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("integer")
                        .HasColumnName("id_trabajo");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("text")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("MontoEstudiante")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_estudiante");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_total");

                    b.Property<decimal>("PorcentajeComision")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_comision");

                    b.HasKey("IdPago");

                    b.HasIndex("IdTrabajo")
                        .IsUnique();

                    b.ToTable("pago");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilAgencia", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("NombreAgencia")
                        .HasColumnType("text")
                        .HasColumnName("nombre_agencia");

                    b.Property<string>("Rubro")
                        .HasColumnType("text")
                        .HasColumnName("rubro");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("text")
                        .HasColumnName("sitio_web");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_agencia");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilCliente", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_cliente");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilEstudiante", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("AnioCursado")
                        .HasColumnType("integer")
                        .HasColumnName("anio_cursado");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("calificacion_promedio");

                    b.Property<int>("CantidadTrabajos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_trabajos");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_estudiante");
                });

            modelBuilder.Entity("Lex.Api.Entities.Postulacion", b =>
                {
                    b.Property<int>("IdPostulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_postulacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPostulacion"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_postulacion");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<decimal?>("MontoPropuesto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_propuesto");

                    b.HasKey("IdPostulacion");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("postulacion");
                });

            modelBuilder.Entity("Lex.Api.Entities.Resena", b =>
                {
                    b.Property<int>("IdResena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_resena");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResena"));

                    b.Property<int>("AutorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("autor_usuario_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("integer")
                        .HasColumnName("id_trabajo");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer")
                        .HasColumnName("puntaje");

                    b.Property<int>("ReceptorUsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("receptor_usuario_id");

                    b.HasKey("IdResena");

                    b.HasIndex("AutorUsuarioId");

                    b.HasIndex("ReceptorUsuarioId");

                    b.HasIndex("IdTrabajo", "AutorUsuarioId")
                        .IsUnique();

                    b.ToTable("resena");
                });

            modelBuilder.Entity("Lex.Api.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("rol");
                });

            modelBuilder.Entity("Lex.Api.Entities.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdServicio"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio");

                    b.Property<int?>("TiempoEntregaDias")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_entrega_dias");

                    b.Property<int>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("IdServicio");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("servicio");
                });

            modelBuilder.Entity("Lex.Api.Entities.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<decimal?>("PresupuestoEstimado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("presupuesto_estimado");

                    b.Property<int?>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("solicitud");
                });

            modelBuilder.Entity("Lex.Api.Entities.TipoInstitucion", b =>
                {
                    b.Property<int>("TipoInstitucionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_institucion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoInstitucionId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("TipoInstitucionId");

                    b.ToTable("tipo_institucion");
                });

            modelBuilder.Entity("Lex.Api.Entities.TipoServicio", b =>
                {
                    b.Property<int>("TipoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoServicioId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequiereSupervision")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_supervision");

                    b.HasKey("TipoServicioId");

                    b.ToTable("tipo_servicio");
                });

            modelBuilder.Entity("Lex.Api.Entities.Trabajo", b =>
                {
                    b.Property<int>("IdTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_trabajo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrabajo"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdPostulacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_postulacion");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto");

                    b.Property<int>("Origen")
                        .HasColumnType("integer")
                        .HasColumnName("origen");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<int?>("TipoServicioId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_servicio_id");

                    b.HasKey("IdTrabajo");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("IdPostulacion");

                    b.HasIndex("IdServicio");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("trabajo");
                });

            modelBuilder.Entity("Lex.Api.Entities.TrabajoHistorial", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorial"));

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("estado_anterior");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("integer")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTrabajo")
                        .HasColumnType("integer")
                        .HasColumnName("id_trabajo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdTrabajo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("trabajo_historial");
                });

            modelBuilder.Entity("Lex.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Lex.Api.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("RolId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_rol");
                });

            modelBuilder.Entity("Lex.Api.Entities.Carrera", b =>
                {
                    b.HasOne("Lex.Api.Entities.Institucion", "Institucion")
                        .WithMany("Carreras")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institucion");
                });

            modelBuilder.Entity("Lex.Api.Entities.Consentimiento", b =>
                {
                    b.HasOne("Lex.Api.Entities.Trabajo", "Trabajo")
                        .WithOne("Consentimiento")
                        .HasForeignKey("Lex.Api.Entities.Consentimiento", "IdTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Paciente", "Paciente")
                        .WithMany("Consentimientos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paciente");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Lex.Api.Entities.DatosEmpresa", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilCliente", "PerfilCliente")
                        .WithOne("DatosEmpresa")
                        .HasForeignKey("Lex.Api.Entities.DatosEmpresa", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilCliente");
                });

            modelBuilder.Entity("Lex.Api.Entities.DatosParticular", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilCliente", "PerfilCliente")
                        .WithOne("DatosParticular")
                        .HasForeignKey("Lex.Api.Entities.DatosParticular", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilCliente");
                });

            modelBuilder.Entity("Lex.Api.Entities.EstudianteCarrera", b =>
                {
                    b.HasOne("Lex.Api.Entities.Carrera", "Carrera")
                        .WithMany("EstudianteCarreras")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("EstudianteCarreras")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Lex.Api.Entities.Institucion", b =>
                {
                    b.HasOne("Lex.Api.Entities.TipoInstitucion", "TipoInstitucion")
                        .WithMany("Instituciones")
                        .HasForeignKey("TipoInstitucionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoInstitucion");
                });

            modelBuilder.Entity("Lex.Api.Entities.Paciente", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilCliente", "Cliente")
                        .WithMany("Pacientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Lex.Api.Entities.Pago", b =>
                {
                    b.HasOne("Lex.Api.Entities.Trabajo", "Trabajo")
                        .WithOne("Pago")
                        .HasForeignKey("Lex.Api.Entities.Pago", "IdTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilAgencia", b =>
                {
                    b.HasOne("Lex.Api.Entities.Usuario", "Usuario")
                        .WithOne("PerfilAgencia")
                        .HasForeignKey("Lex.Api.Entities.PerfilAgencia", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilCliente", b =>
                {
                    b.HasOne("Lex.Api.Entities.Usuario", "Usuario")
                        .WithOne("PerfilCliente")
                        .HasForeignKey("Lex.Api.Entities.PerfilCliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilEstudiante", b =>
                {
                    b.HasOne("Lex.Api.Entities.Usuario", "Usuario")
                        .WithOne("PerfilEstudiante")
                        .HasForeignKey("Lex.Api.Entities.PerfilEstudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Entities.Postulacion", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("Postulaciones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Solicitud", "Solicitud")
                        .WithMany("Postulaciones")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Lex.Api.Entities.Resena", b =>
                {
                    b.HasOne("Lex.Api.Entities.Usuario", "Autor")
                        .WithMany("ResenasComoAutor")
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Trabajo", "Trabajo")
                        .WithMany("Resenas")
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Usuario", "Receptor")
                        .WithMany("ResenasComoReceptor")
                        .HasForeignKey("ReceptorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Receptor");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Lex.Api.Entities.Servicio", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("Servicios")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.TipoServicio", "TipoServicio")
                        .WithMany("Servicios")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("Lex.Api.Entities.Solicitud", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilCliente", "Cliente")
                        .WithMany("Solicitudes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.TipoServicio", "TipoServicio")
                        .WithMany("Solicitudes")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("Lex.Api.Entities.Trabajo", b =>
                {
                    b.HasOne("Lex.Api.Entities.PerfilCliente", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.PerfilEstudiante", "Estudiante")
                        .WithMany("Trabajos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Postulacion", "Postulacion")
                        .WithMany("Trabajos")
                        .HasForeignKey("IdPostulacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lex.Api.Entities.Servicio", "Servicio")
                        .WithMany("Trabajos")
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lex.Api.Entities.Paciente", "Paciente")
                        .WithMany("Trabajos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lex.Api.Entities.TipoServicio", "TipoServicio")
                        .WithMany("Trabajos")
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Estudiante");

                    b.Navigation("Paciente");

                    b.Navigation("Postulacion");

                    b.Navigation("Servicio");

                    b.Navigation("TipoServicio");
                });

            modelBuilder.Entity("Lex.Api.Entities.TrabajoHistorial", b =>
                {
                    b.HasOne("Lex.Api.Entities.Trabajo", "Trabajo")
                        .WithMany("Historiales")
                        .HasForeignKey("IdTrabajo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Usuario", "Usuario")
                        .WithMany("TrabajoHistoriales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Trabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Lex.Api.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lex.Api.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lex.Api.Entities.Carrera", b =>
                {
                    b.Navigation("EstudianteCarreras");
                });

            modelBuilder.Entity("Lex.Api.Entities.Institucion", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("Lex.Api.Entities.Paciente", b =>
                {
                    b.Navigation("Consentimientos");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilCliente", b =>
                {
                    b.Navigation("DatosEmpresa");

                    b.Navigation("DatosParticular");

                    b.Navigation("Pacientes");

                    b.Navigation("Solicitudes");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Entities.PerfilEstudiante", b =>
                {
                    b.Navigation("EstudianteCarreras");

                    b.Navigation("Postulaciones");

                    b.Navigation("Servicios");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Entities.Postulacion", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Lex.Api.Entities.Servicio", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Entities.Solicitud", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("Lex.Api.Entities.TipoInstitucion", b =>
                {
                    b.Navigation("Instituciones");
                });

            modelBuilder.Entity("Lex.Api.Entities.TipoServicio", b =>
                {
                    b.Navigation("Servicios");

                    b.Navigation("Solicitudes");

                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Lex.Api.Entities.Trabajo", b =>
                {
                    b.Navigation("Consentimiento");

                    b.Navigation("Historiales");

                    b.Navigation("Pago");

                    b.Navigation("Resenas");
                });

            modelBuilder.Entity("Lex.Api.Entities.Usuario", b =>
                {
                    b.Navigation("PerfilAgencia");

                    b.Navigation("PerfilCliente");

                    b.Navigation("PerfilEstudiante");

                    b.Navigation("ResenasComoAutor");

                    b.Navigation("ResenasComoReceptor");

                    b.Navigation("TrabajoHistoriales");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
